### ISSUE TITLE
DND

### ISSUE THREAD

**Issue by fiorentino77** [Home-Assistant-Pro-Team/Power-Control-HomeAssistant#2]
E' possibile impostare un intervallo di silenzio nelle notifiche?
Grazie.

**Comment by marco-hacs** [comment]
cosa intendi? una fascia oraria per non ricevere notifiche? Questa necessità, è solo per i media_player o anche push? Per i media, la vedo sensata... push un po meno.

comunque puoi aggiungere nel file notify_media_control_power.yaml e notify_push_xxxx la condizione oraria 
```
  - condition: time
    after: "22:00:00"
    before: "07:00:00"
```
![Screenshot 2023-07-01 154814](https://github.com/Home-Assistant-Pro-Team/Power-Control/assets/62516592/d94b532f-8c36-41f1-8f7c-2e8bdf2599e5)

**Comment by fiorentino77** [comment]
Si, intendevo per i media_player magari selezionabile da UI. Grazie

**Comment by marco-hacs** [comment]
magari nel prossimo fix lo aggiungiamo... per ora puoi modificarlo da yaml come scritto sopra

**Comment by marco-hacs** [comment]
E' stata aggiunta la funzione richiesta, non da UI, ma puoi personalizzare orario da `notify_media_control_power.yaml`. 

![image](https://github.com/Home-Assistant-Pro-Team/Power-Control-HomeAssistant/assets/62516592/20226151-2fe8-456a-852e-fccb586ae3af)
