### ISSUE TITLE
Entità da escludere per irpristino carico non visibili

### ISSUE THREAD

**Issue by ady1972** [Home-Assistant-Pro-Team/Power-Control-HomeAssistant#7]
Grazie innanzitutto per lo splendido add-on.
Ho seguito le istruzioni alla lettera e tutto sembra essere ok. Ho notato però che ,cliccando sull'opzione relativa ai carichi da escludere per ripristino, non compare nessuna entità di quelle che ho inserito nel file power_control.jinja...Quindi mi sorge anche il dubbio che non siano state configurate neanche per il distacco delle stesse...
Cosa dovrei controllare per una verifica?

Grazie in anticipo

**Comment by marco-hacs** [comment]
Nello stesso popup dovresti trovarti compilato la "Lista carichi". Se non vuota mostra come hai configurato i dispositivi in coustom_template/power_control.jinja 

![list](example/list.png)

**Comment by ady1972** [comment]
Ciao

innanzitutto ti ringrazio per la risposta veloce.
Ti allego il file editato con le entità.
Avrò sicuramente commesso qualche errore ma non riesco a capire dove di
preciso.
Ti ringrazio nuovamente in anticipo

Ciao

Andrea

Il giorno mer 15 nov 2023 alle ore 11:44 Marco ***@***.***>
ha scritto:

**Comment by marco-hacs** [comment]
devi metterla qui. non puoi allegare per mail.

**Comment by ady1972** [comment]
Chiedo scusa

Eccolo

{% set list_entities =
    [
       'switch.stufa_bagno_outlet',
       'switch.lavatrice_outlet',
       'switch.presa_friggitrice'
    ]
%}

{% macro power_control() %}
{
"Sensore W": "sensor.shelly_shem_34945473d1a3_1_current_consumption"
}
{% endmacro %}

##############################################################
#         DA QUESTO PUNTO NON MODIFICARE
##############################################################

{% macro entities_control() %}
    {% for d in list_entities %}
        {{ d }}
    {% endfor %}
{% endmacro %}

{% macro list_device() %}
    {% set output = namespace(sensor_power_off=[],result=[]) %}
    {# escludi spenti e non disponibili #}
    {%- set filter = states | selectattr('entity_id', 'in', list_entities)
| rejectattr('state', 'in',['off', 'unavailable', 'unknown']) |
map(attribute='entity_id') | list-%}
    {# lista filtrate ed ordinata #}
    {%-  for on_power_off in list_entities if on_power_off in filter  -%}
        {# recupera id dispositivo #}
        {% set id = device_id(on_power_off)%}
        {# Restituisci entity_id del sensore power se associato #}
        {%- set sensor_power =expand(device_entities(id)) |
selectattr('entity_id', 'match', 'sensor.') |
selectattr('attributes.device_class', 'defined') |
selectattr('attributes.device_class', 'eq', 'power') |
map(attribute='entity_id') | list %}
        {# controlla che assorbimento sia minore di 15W #}
        {%- for power in sensor_power if states(power) | int(0) < 15 -%}
            {# entità nella lista in stato ON con sensore di potenza
inferiore a 15W #}
            {%- set output.sensor_power_off = output.sensor_power_off +
[on_power_off] -%}
        {% endfor %}
    {% endfor %}
    {# ottieni le entità ordinate da spegnere #}
    {% for t in list_entities if t in filter and not t in
output.sensor_power_off %}
        {{t}}
    {% endfor %}
{% endmacro %}

Il giorno mer 15 nov 2023 alle ore 12:09 Marco ***@***.***>
ha scritto:

**Comment by marco-hacs** [comment]
Sembra corretto... Ma nella schermata che ho messo prima, hai la lista dei dispositivi?

**Comment by ady1972** [comment]
Non sono riuscito a vedere la schermata che hai postato in quanto mi
compare un link e non lo apre. Ecco la mia comunque. Non vedendo nessun
dispositivo elencato ho pensato che fosse un problema di compilazione del
file

[image: image.png]

Il giorno mer 15 nov 2023 alle ore 12:15 Marco ***@***.***>
ha scritto:

**Comment by ady1972** [comment]
Ciao
Ho scoperto dove ho sbagliato.
Ho erroneamente inserito i due file nella cartella custom _components...
Dalla smania di provare il tutto non ho vissuto che invece andava creata
una nuova custom_templates.
Ti chiedo scusa per il disturbo e ti ringrazio per il pronto auto.

Buon pomeriggio

Ciao

Andrea

Il mer 15 nov 2023, 12:15 Marco ***@***.***> ha scritto:
