### ISSUE TITLE
Button 1 e 2 non funzionano

### ISSUE THREAD

**Issue by lucariello78** [Home-Assistant-Pro-Team/Power-Control-HomeAssistant#9]
Ciao, intanto complimenti per l'utilissima configurazione, ho seguito tutti i passaggi, ho installato le integnazioni che non avevo (Apexcharts card e Mushroom) ed ho creato la card.

Adesso vedo la card con tutti i dati ma se clicco i primi 2 button (quello con la lista dei dispositivi e quello con i settings) non succede nulla mentre invece gli altri due cliccandoli si attivano e disattivano. Le varie entità le vedo in HA (tipo [input_number.distacco_carico]) ma non riesco a configurarle da interfaccia perché non mi si aprono.

Secondo te cosa ho sbagliato?

Grazie
Luca

**Comment by marco-hacs** [comment]
Devi installare browser mode come requisito card nel readmi. Se già lo hai fatto cancella cache del browser.

**Comment by lucariello78** [comment]
ah ecco adesso funziona! non avevo configurato bene browser mode, ce l'avevo già installato e non ho approfondito.

Grazie mille!
